### ISSUE TITLE
Add automatic logout when devise token expires

### ISSUE THREAD

**Issue by GuilleLeopold** [rootstrap/ios-base#70] opened 2018-01-02 16:03 UTC
Once the devise token expires in the backend, the ios app should be automatically logged out.

Right now when the token expires, the app gets stuck as the session doesn't close and the user is not able to do any action (including logout)

**Comment by glm4** [comment] 2018-01-03 19:17
Duplicate of #65

**Comment by glm4** [comment] 2018-01-08 18:18
Solved in #72. Closing...

**Comment by glm4** [comment] 2018-01-08 18:18
Solved in #72. Closing...

**Closed by glm4** 2018-01-08 18:18 UTC
Labels: duplicate
